const fs = require('node:fs')
const path = require('node:path')
const { execFileSync } = require('node:child_process')
const pkg = require('../package.json')

const stage = path.resolve('release/package')
fs.rmSync(path.resolve('release'), { recursive: true, force: true })
fs.mkdirSync(path.join(stage, 'dist'), { recursive: true })
fs.mkdirSync(path.join(stage, 'companion'), { recursive: true })
for (const file of ['package.json', 'LICENSE']) fs.copyFileSync(file, path.join(stage, file))
for (const file of ['manifest.json', 'HELP.md']) fs.copyFileSync(path.join('companion', file), path.join(stage, 'companion', file))
for (const file of ['index.js', 'index.js.map']) fs.copyFileSync(path.join('dist', file), path.join(stage, 'dist', file))
const output = path.resolve(`release/fora-cc-${pkg.version}.tgz`)
execFileSync('tar', ['-czf', output, '-C', path.resolve('release'), 'package'])
console.log(output)
